global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: fluxlens-api-gateway
    static_configs:
      - targets: ["host.docker.internal:8090"]
        labels:
          service: api-gateway

  - job_name: fluxlens-curator
    static_configs:
      - targets: ["host.docker.internal:8091"]
        labels:
          service: curator

  - job_name: fluxlens-orchestrator
    static_configs:
      - targets: ["host.docker.internal:8092"]
        labels:
          service: orchestrator

  - job_name: fluxlens-audit-writer
    static_configs:
      - targets: ["host.docker.internal:8093"]
        labels:
          service: audit-writer

  - job_name: fluxlens-ingest-mysql
    static_configs:
      - targets: ["host.docker.internal:8094"]
        labels:
          service: ingest-mysql
